version: '3.5'

services:
  node1:
    image: node:lts-bullseye
    container_name: tenten-bfs-n1
    hostname: tenten-bfs-n1
    networks:
      bridge0:
        ipv4_address: 10.5.82.11
    volumes:
      - type: bind
        source: ./source
        target: /mnt/source
    cpus: 2.0
    mem_limit: 1024m
    memswap_limit: 1024m
    restart: unless-stopped
    tty: true
    logging:
      driver: none

  node2:
    image: node:lts-bullseye
    container_name: tenten-bfs-n2
    hostname: tenten-bfs-n2
    networks:
      bridge0:
        ipv4_address: 10.5.82.12
    volumes:
      - type: bind
        source: ./source
        target: /mnt/source
    cpus: 2.0
    mem_limit: 1024m
    memswap_limit: 1024m
    restart: unless-stopped
    tty: true
    logging:
      driver: none

  node3:
    image: node:lts-bullseye
    container_name: tenten-bfs-n3
    hostname: tenten-bfs-n3
    networks:
      bridge0:
        ipv4_address: 10.5.82.13
    volumes:
      - type: bind
        source: ./source
        target: /mnt/source
    cpus: 2.0
    mem_limit: 1024m
    memswap_limit: 1024m
    restart: unless-stopped
    tty: true
    logging:
      driver: none

  node4:
    image: node:lts-bullseye
    container_name: tenten-bfs-n4
    hostname: tenten-bfs-n4
    networks:
      bridge0:
        ipv4_address: 10.5.82.14
    volumes:
      - type: bind
        source: ./source
        target: /mnt/source
    cpus: 2.0
    mem_limit: 1024m
    memswap_limit: 1024m
    restart: unless-stopped
    tty: true
    logging:
      driver: none

networks:
  bridge0:
    external: true
