version: '3'
services:
  city1:
    build: .
    environment:
      - CITY_ID=1
  city2:
    build: .
    environment:
      - CITY_ID=2
  city3:
    build: .
    environment:
      - CITY_ID=3
  city4:
    build: .
    environment:
      - CITY_ID=4
