version: '3'

services:
  city1:
    build: .
    environment:
      CITY_NUMBER: 1
      PORT: 5001
    networks:
      my_network:
        ipv4_address: 172.28.1.1

  city2:
    build: .
    environment:
      CITY_NUMBER: 2
      PORT: 5002
    networks:
      my_network:
        ipv4_address: 172.28.1.2

  city3:
    build: .
    environment:
      CITY_NUMBER: 3
      PORT: 5003
    networks:
      my_network:
        ipv4_address: 172.28.1.3

  city4:
    build: .
    environment:
      CITY_NUMBER: 4
      PORT: 5004
    networks:
      my_network:
        ipv4_address: 172.28.1.4

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
